# **FRAMEWORKS DE DEEPLEARNING**
# **Prática - PyTorch**
**Autor**: Renan Santos Mendes

**Email**: renansantosmendes@gmail.com

**Descrição**: Este notebook apresenta uma introdução ao framework PyTorch.

In [2]:
!pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126
   ---------------------------------------- 0.0/2.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 GB 57.3 MB/s eta 0:00:46
   ---------------------------------------- 0.0/2.6 GB 60.2 MB/s eta 0:00:44
    --------------------------------------- 0.0/2.6 GB 59.1 MB/s eta 0:00:44
    --------------------------------------- 0.0/2.6 GB 58.1 MB/s eta 0:00:45
    --------------------------------------- 0.1/2.6 GB 61.0 MB/s eta 0:00:42
   - -------------------------------------- 0.1/2.6 GB 60.7 MB/s eta 0:00:42
   - -------------------------------------- 0.1/2.6 GB 62.1 MB/s eta 0:00:41
   - -------------------------------------- 0.1/2.6 GB 66.2 MB/s eta 0:00:38
   -- ------------------------------------- 0.1/2.6 GB 72.1 MB/s eta 0:00:35
   -- ------------------------------------- 0.2/2.6 GB 76.8 MB/s eta 0:00:33
   -- ------------------------------------- 0.2/2.6 GB 80.6 MB/s eta 0:00:31
   --- ------------------

In [4]:
import torch

In [5]:
torch.__version__

'2.12.0+cu126'

In [10]:
tensor_1 = torch.Tensor([1, 2, 3])

In [11]:
tensor_1

tensor([1., 2., 3.])

In [13]:
tensor_1.nelement()

3

 ## **Tipos de Tensores**

In [14]:
torch.IntTensor([1, 2, 3])

tensor([1, 2, 3], dtype=torch.int32)

In [15]:
torch.FloatTensor([1, 2, 3])

tensor([1., 2., 3.])

In [16]:
torch.BoolTensor([1, 2, 3])

tensor([True, True, True])

In [17]:
complex_tensor = torch.randn(1,2)

In [18]:
complex_tensor

tensor([[1.7331, 1.1063]])

In [22]:
complex_tensor[0][0]

tensor(1.7331)

In [25]:
complex_tensor.squeeze().shape

torch.Size([2])

In [19]:
complex(1,2)

(1+2j)

In [20]:
torch.view_as_complex(complex_tensor)

tensor([1.7331+1.1063j])

 ## **Conversão entre tipos de tensores**

In [26]:
tensor_1.bool()

tensor([True, True, True])

In [27]:
tensor_1.half()

tensor([1., 2., 3.], dtype=torch.float16)

In [28]:
tensor_1.bfloat16()

tensor([1., 2., 3.], dtype=torch.bfloat16)

 ## **Operações**

In [ ]:
tensor_a = torch.Tensor([1, 2, 3])
tensor_b = torch.Tensor([4, 5, 6])

####**Adição**

####**Subtração**

####**Multiplicação**

####**Divisão**

##**Operações Matriciais**

In [ ]:
tensor_1 = torch.Tensor([[1, 4]])

tensor_2 = torch.Tensor([[1, -2], [3, 2]])

In [ ]:
...

## **Operações Tensoriais**

####**Divisão**

## **Gradientes e Autograd**

In [ ]:
x =

$f(x) = x^3$

$\frac{d f(x)}{dx} = 3x^2 = 3(2)^2 = 12$

In [ ]:
...

####**Grafo do Tensor**

In [ ]:
%%capture
!pip install torchviz
!apt-get install graphviz -qq

In [ ]:
import torch
from torchviz import make_dot
from IPython.display import display

In [ ]:
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(3, 4, requires_grad=True)
z = x @ y
loss = z.sum()

dot = make_dot(loss, params={'x': x, 'y': y})
display(dot)