# **FRAMEWORKS DE DEEPLEARNING**
# **Prática - PyTorch**
**Autor**: Renan Santos Mendes

**Email**: renansantosmendes@gmail.com

**Descrição**: Este notebook apresenta uma introdução ao framework PyTorch.

In [1]:
import torch

In [ ]:
torch.__version__

'2.11.0+cpu'

In [ ]:
tensor_1 = torch.Tensor([1, 2, 3])

In [ ]:
tensor_1

tensor([1., 2., 3.])

In [ ]:
tensor_1.nelement()

3

In [ ]:
tensor_1.dtype

torch.float32

In [ ]:
tensor_1.shape

torch.Size([3])

 ## **Tipos de Tensores**

In [ ]:
torch.IntTensor([1, 2, 3])

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.FloatTensor([1, 2, 3])

tensor([1., 2., 3.])

In [ ]:
torch.BoolTensor([1, 0, 0])

tensor([ True, False, False])

In [ ]:
complex_tensor = torch.randn(1,2)

In [ ]:
complex_tensor.shape

torch.Size([1, 2])

In [ ]:
complex_tensor[0][0]

tensor(-0.7146)

In [ ]:
complex(1, 2)

(1+2j)

In [ ]:
torch.view_as_complex(complex_tensor)

tensor([-0.7146+1.0799j])

In [ ]:
complex_tensor.squeeze().shape

torch.Size([2])

 ## **Conversão entre tipos de tensores**

In [ ]:
tensor_1.bool()

tensor([True, True, True])

In [ ]:
tensor_1.half()

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
tensor_1.bfloat16()

tensor([1., 2., 3.], dtype=torch.bfloat16)

In [ ]:
import torch

def print_tensor_info(name, tensor):
    bits = tensor.element_size() * 8
    print(f"{name:10} | Dtype: {str(tensor.dtype):15} | Bits por elemento: {bits}")

t1 = torch.tensor([1, 2, 3], dtype=torch.float32)
t2 = t1.half()     # float16
t3 = t1.bfloat16() # bfloat16
t4 = t1.to(torch.int8)

print_tensor_info("Tensor 1", t1)
print_tensor_info("Tensor 2", t2)
print_tensor_info("Tensor 3", t3)
print_tensor_info("Tensor 4", t4)

Tensor 1   | Dtype: torch.float32   | Bits por elemento: 32
Tensor 2   | Dtype: torch.float16   | Bits por elemento: 16
Tensor 3   | Dtype: torch.bfloat16  | Bits por elemento: 16
Tensor 4   | Dtype: torch.int8      | Bits por elemento: 8


 ## **Operações**

In [ ]:
tensor_a = torch.Tensor([1, 2, 3])
tensor_b = torch.Tensor([4, 5, 6])

####**Adição**

####**Subtração**

####**Multiplicação**

####**Divisão**

##**Operações Matriciais**

In [ ]:
tensor_1 = torch.Tensor([[1, 4]])

tensor_2 = torch.Tensor([[1, -2], [3, 2]])

In [ ]:
...

## **Operações Tensoriais**

####**Divisão**

## **Gradientes e Autograd**

In [ ]:
x =

$f(x) = x^3$

$\frac{d f(x)}{dx} = 3x^2 = 3(2)^2 = 12$

In [ ]:
...

####**Grafo do Tensor**

In [ ]:
%%capture
!pip install torchviz
!apt-get install graphviz -qq

In [ ]:
import torch
from torchviz import make_dot
from IPython.display import display

In [ ]:
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(3, 4, requires_grad=True)
z = x @ y
loss = z.sum()

dot = make_dot(loss, params={'x': x, 'y': y})
display(dot)